services:

    #
    # Twig renderer
    #
    elcodi_plugin.product_csv.renderer:
        class: %elcodi_plugin.product_csv.renderer.class%
        calls:
            - [setTemplating, [@twig]]
        tags:
            - { name: kernel.event_listener, event: admin.header_actions, method: renderButtons }
